name: Node.js CI

on:
  push:
    branches:
      - main  # Runs on push to the main branch (can be changed to your default branch)
  pull_request:
    branches:
      - main  # Runs on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # You can specify your Node.js version here

    - name: Install dependencies
      run: npm install


    #- name: Run tests
     # run: npm test  # Adjust this command if you have a custom test script

    #- name: Lint code
    #  run: npm run lint  # If you have linting configured

    #- name: Build the app (if applicable)
    #  run: npm run build  # If you have a build step, include it

    #- name: Deploy (optional)
     # run: |
      #  echo "Deploying your app..."
        # Add your deployment script here if applicable
